name: CI/CD Pipeline

on:
  workflow_dispatch: # Permite executar manualmente o pipeline

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Configuração do Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Passo 3: Instalar Maven (caso ./mvnw tenha problemas)
      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      # Passo 4: Rodar testes (substituí ./mvnw por mvn caso o wrapper falhe)
      - name: Run tests
        run: mvn test

      # Passo 5: Build do JAR (ignorar testes aqui, já rodaram no passo anterior)
      - name: Build JAR
        run: mvn clean package -DskipTests

      # Passo 6: Login no DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Passo 7: Build da imagem Docker
      - name: Build Docker Image
        run: docker build -t myapp:latest .

      # Passo 8: Push da imagem para o DockerHub
      - name: Push Docker Image
        run: docker push myapp:latest
