name: CI/CD Pipeline

on:
  workflow_dispatch: # Permite executar manualmente o pipeline

jobs:
  # Job 1: Testar e construir o projeto
  prepare-and-build:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Clonar o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Etapa 2: Configurar o JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Etapa 3: Cache das dependências do Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Etapa 4: Rodar testes e buildar o projeto
      - name: Run tests and build
        run: cd gourmet-inventory-project && mvn clean package -DskipTests -DfinalName=gourmet-inventory-project -Dmaven.repo.local=~/.m2/repository

      # Salvar o jar como artefato para compartilhar com outros jobs
      - name: Upload jar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: gourmet-inventory-jar
          path: gourmet-inventory-project/target/gourmet-inventory-project.jar

  # Job 2: Fazer login no Docker Hub
  docker-login:
    runs-on: ubuntu-latest
    needs: prepare-and-build # Este job só executa após o sucesso do prepare-and-build

    steps:
      # Etapa 1: Fazer login no Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  # Job 3: Construir e enviar a imagem Docker
  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: [prepare-and-build, docker-login] # Este job só executa após os outros dois jobs

    steps:
      # Etapa 1: Baixar o jar gerado no job anterior
      - name: Download jar artifact
        uses: actions/download-artifact@v3
        with:
          name: gourmet-inventory-jar

      # Etapa 2.1: ls teste
      - name: ls -la teste
        run: ls -la

      # Etapa 2: Construir a imagem Docker
      - name: Build Docker image
        run: docker build -t voltty/gourmet-inventory:latest .

      # Etapa 3: Enviar a imagem Docker para o Docker Hub
      - name: Push Docker image
        run: docker push voltty/gourmet-inventory:latest
